GroceryHub/Models/Offer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryHub.Models
{
    public class Offer
    {
        [Key]
        public int OfferID { get; set; }
        public Double Unit { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Currency)]
        public Double Price { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Due Date")]
        public DateTime DueDate { get; set; }
        [Range(0, 5)]
        [Display(Name = "Level")]
        public int Level { get; set; }

        [Display(Name = "Description")]
        public String OfferDescription { get; set; }

        public bool IsValid { get; set; } = true;

        public Store Store { get; set; }
        public int StoreID { get; set; }

        public Item Item { get; set; }
        public int ItemID { get; set; }

        public List<CartItem> cartItems { get; set; } = new List<CartItem>();
    }
}

GroceryHub/ViewModels/OfferViewModel.cs
using GroceryHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryHub.ViewModels
{
    public class OfferViewModel
    {
        public Offer Offer { get; set; }
    }
}

GroceryHub/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GroceryHub.Data;
using GroceryHub.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace GroceryHub.Controllers
{
    public class OffersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public OffersController(ApplicationDbContext context, UserManager<AppUser> userManager )
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Offers
        public async Task<IActionResult> Index(int? id, string? val, int pageNumber =1)
        {
            ValidateOffers();
            OfferRatingSystem();
            if (val == "Store")
            {
                var applicationDbContext = _context.Offer.Include(o => o.Item)
                    .Include(o => o.Store).Where(a => a.StoreID == id)
                    .Where(o => o.IsValid == true);

                return View("Index", await PaginatedList<Offer>.CreateAsync(applicationDbContext, pageNumber, 18));
            }
            else if(val == "Item")
            {
                if (_context.Offer.Where(i => i.ItemID == id).Count() > 0 && _context.Offer.Where(i => i.ItemID == id) != null)
                {
                    ViewBag.BestPrice = _context.Offer.Where(i=>i.ItemID == id).Include(x=>x.Item).OrderBy(a => a.Price).First();
                }

                return View("Index", await PaginatedList<Offer>.CreateAsync(_context.Offer.Include(o => o.Item)
                    .Include(o => o.Store).Where(a => a.ItemID == id)
                    .Where(o => o.IsValid == true), pageNumber, 18));
            }
            else
            {
                return View(await PaginatedList<Offer>.CreateAsync(_context.Offer.Include(o => o.Item)
                    .Include(o => o.Store).Where(a => a.IsValid == true), pageNumber, 18));
            }
        }

        public void OfferRatingSystem()
        {
            foreach(Item item in _context.Item)
            {
                if (item.Offers != null)
                {
                    var avg = item.Offers.Select(x => x.Price).DefaultIfEmpty(0).Average();
                    var lowestPrice = item.Offers.OrderBy(i => i.Price).FirstOrDefault().Price;
                    var highstPrice = item.Offers.OrderByDescending(i => i.Price).FirstOrDefault().Price;

                    foreach (Offer offer in item.Offers)
                    {
                        if (offer.Price >= highstPrice)
                        {
                            offer.Level = 1;
                            _context.Update(offer);
                        }
                        else if (offer.Price > avg && offer.Price < highstPrice)
                        {
                            offer.Level = 2;
                            _context.Update(offer);
                        }
                        else if (offer.Price == avg)
                        {
                            offer.Level = 3;
                            _context.Update(offer);
                        }
                        else if (offer.Price < avg && offer.Price > lowestPrice)
                        {
                            offer.Level = 4;
                            _context.Update(offer);
                        }
                        else if (offer.Price <= lowestPrice)
                        {
                            offer.Level = 5;
                            _context.Update(offer);
                        }
                    }
                }
            }
            _context.SaveChanges();
        }

        [Authorize]
        public async Task<JsonResult> AddToCart(int? id)
        {
            if (id == 0)
            {
                return Json(new { success = true, msg = "Exist" });

            }
            Offer offer = await _context.Offer.Include(o => o.cartItems)
                .Include(i => i.Item).Include(s => s.Store)
                .FirstOrDefaultAsync(m => m.OfferID == id);

            AppUser user = await _userManager.GetUserAsync(HttpContext.User);

            var currentUser = _context.Users.Include(u => u.Cart).
                ThenInclude(m=>m.CartItems).ThenInclude(o => o.Offer).First(i => i.UserName == user.UserName);

            if (currentUser.Cart == null)
            {
                Cart tempCart = new Cart
                {
                    AppUser = currentUser,
                    AppUserID = currentUser.Id,
                    CartItems = new List<CartItem>()
                };

                _context.Cart.Add(tempCart);
                _context.SaveChanges();

                currentUser.CartID = tempCart.CartID;
                currentUser.Cart = tempCart;
                IdentityResult result1 = await _userManager.UpdateAsync(currentUser);
                _context.SaveChanges();
            }

            if (currentUser.Cart.CartItems.FirstOrDefault(o => o.Offer.OfferID == offer.OfferID) != null)
            {
                ViewBag.Message = "Exist";
                return Json(new { success = true, msg = "Exist" });

            }

            else
            {
                CartItem cartItem = new CartItem
                {
                    Cart = currentUser.Cart,
                    CartID = currentUser.Cart.CartID,
                    Offer = offer,
                    OfferID = offer.OfferID
                };

                currentUser.Cart.CartItems.Add(cartItem);
                offer.cartItems.Add(cartItem);

                _context.CartItem.Add(cartItem);
                IdentityResult result = await _userManager.UpdateAsync(currentUser);
                _context.SaveChanges();
                ViewBag.Message = "Added";
                return Json(new { success = true, msg = "Added" });
            }
        }

        // GET: Offers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.Item)
                .Include(o => o.Store)
                .FirstOrDefaultAsync(m => m.OfferID == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }
        [Authorize(Roles = "Admin")]
        // GET: Offers/Create
        public IActionResult Create()
        {
            ViewData["ItemID"] = new SelectList(_context.Item, "ItemID", "ItemName");
            ViewData["StoreID"] = new SelectList(_context.Store, "StoreID", "StoreName");
            return View();
        }

        // POST: Offers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("OfferID,Unit,Price,StartDate,DueDate,Level,OfferDescription,IsValid,StoreID,ItemID")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                bool a=offer.IsValid;
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemID"] = new SelectList(_context.Item, "ItemID", "ItemName", offer.ItemID);
            ViewData["StoreID"] = new SelectList(_context.Store, "StoreID", "StoreName", offer.StoreID);
            return View(offer);
        }




        // GET: Offers/Edit/5    
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
            ViewData["ItemID"] = new SelectList(_context.Item, "ItemID", "ItemName", offer.ItemID);
            ViewData["StoreID"] = new SelectList(_context.Store, "StoreID", "StoreName", offer.StoreID);
            return View(offer);
        }

        // POST: Offers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("OfferID,Unit,Price,StartDate,DueDate,Level,OfferDescription,IsValid,StoreID,ItemID")] Offer offer)
        {
            if (id != offer.OfferID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.OfferID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemID"] = new SelectList(_context.Item, "ItemID", "ItemName", offer.ItemID);
            ViewData["StoreID"] = new SelectList(_context.Store, "StoreID", "StoreName", offer.StoreID);
            return View(offer);
        }

GroceryHub/Views/Offers/Create.cshtml
@model GroceryHub.Models.Offer

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-lg-12 col-xl-12">
        <div class="card shadow mb-3">
            <div class="card-header py-3">
                <p class="m-0 font-weight-bold" style="color: #89ab2a;">Creat new&nbsp;</p>
            </div>
            <div class="card-body">
                <form asp-action="Create" method="post" asp-controller="Offers">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-row">



                        <div class="col-lg-6">
                            <div class="form-group">
                                <strong>
                                    <label asp-for="Price" class="control-label"></label>
                                </strong>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <strong>
                                    <label asp-for="OfferDescription" class="control-label"></label>
                                </strong>
                                <input asp-for="OfferDescription" class="form-control" />
                                <span asp-validation-for="OfferDescription" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">

                        <div class="col-lg-6">
                            <div class="form-group">
                                <strong>
                                    <label asp-for="StartDate" class="control-label"></label>
                                </strong>
                                <input asp-for="StartDate" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <strong>
                                    <label asp-for="DueDate" class="control-label"></label>
                                </strong>
                                <input asp-for="DueDate" class="form-control" />
                                <span asp-validation-for="DueDate" class="text-danger"></span>
                            </div>
                        </div>

                    </div>

                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <strong>

                                    <label asp-for="StoreID" class="control-label"></label>
                                </strong>

                                <select asp-for="StoreID" class="form-control" asp-items="ViewBag.StoreID"></select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <strong>

                                    <label asp-for="ItemID" class="control-label"></label>
                                </strong>

                                <select asp-for="ItemID" class="form-control" asp-items="ViewBag.ItemID"></select>
                            </div>
                        </div>
                    </div>



                    <div class="form-row">

                        @*<div class="col-lg-6">
                <div class="form-group">
                    <strong>
                        <label asp-for="Level" class="control-label"></label>
                    </strong>
                    <input asp-for="Level" class="form-control" />
                    <span asp-validation-for="Level" class="text-danger"></span>
                </div>
            </div>*@
                        @*<div class="col-lg-6">
                            <div class="form-group">
                                <strong><label asp-for="Unit" class="control-label"></label></strong>
                                <input asp-for="Unit" class="form-control" />
                                <span asp-validation-for="Unit" class="text-danger"></span>
                            </div>
                        </div>*@


                    </div>


                    @*<div class="form-row">

            <div class="col-lg-6">
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsValid" /> @Html.DisplayNameFor(model => model.IsValid)
                    </label>
                </div>
            </div>

        </div>*@


                    <div class="form-group text-right">
                        <input class="btn btn-primary btn-sm" type="submit" value="Create" style="background-color: #89ab2a;" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GroceryHub/Views/Offers/Delete.cshtml
@model GroceryHub.Models.Offer

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-lg-12 col-xl-12">
        <div class="card shadow mb-3">
            <div class="card-header py-3">
                <p class="m-0 font-weight-bold" style="color: #89ab2a;">Delete&nbsp;</p>
            </div>
            <div class="card-body">

                <h3>Are you sure you want to delete this?</h3>
                <div>
                    <h4>Offer</h4>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Unit)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Unit)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Price)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.StartDate)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.StartDate)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.DueDate)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.DueDate)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Level)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Level)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.OfferDescription)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.OfferDescription)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.IsValid)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.IsValid)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.Location)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Item)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Item.ItemName)
                        </dd>
                    </dl>

                    <form asp-action="Delete">
                        <input type="hidden" asp-for="OfferID" />
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <a asp-action="Index">Back to List</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

GroceryHub/Views/Offers/Details.cshtml
@model GroceryHub.Models.Offer

@{
    ViewData["Title"] = "Details";
}

    <div class="row">
        <div class="col-lg-6 col-xl-6">
            <div class="card shadow mb-3">
                <div class="card-header py-3">
                    <p class="m-0 font-weight-bold" style="color: #89ab2a;">Offer Details&nbsp;</p>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Unit)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Unit)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Price)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.StartDate)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.StartDate)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.DueDate)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.DueDate)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Level)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Level)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.OfferDescription)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.OfferDescription)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.IsValid)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.IsValid)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.Location)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Item)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Item.ItemName)
                        </dd>
                    </dl>
                </div>
                <div class="mb-2">
                    <a class="btn btn-success btn-sm " asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-xl-6">
            <div class="card shadow mb-3">
                <div class="card-header py-3">
                    <p class="m-0 font-weight-bold" style="color: #89ab2a;">Store Details&nbsp;</p>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.StoreName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.StoreName)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.Location)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.Location)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.Rate)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.Rate)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.Website)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.Website)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.PhoneNumber)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.PhoneNumber)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.OpenHour)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.OpenHour)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.CloseHour)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.CloseHour)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.Type)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Store.Type)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Store.Image)
                        </dt>
                        <dd class="col-sm-10">
                            @if (Model.Store.Image != null)
                            {<img class="rounded-circle mr-2" width="50" height="50" src="data:image/png;base64,@Convert.ToBase64String(Model.Store.Image)" />}
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>